import functions_framework
import json
import logging
import re

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def evaluate_product_match(model_response_text, ground_truth):
    """
    Evaluates alignment between the model's reported 'product_match' 
    and the ground truth from the CSV.
    
    Returns a score: A simple 1.0 (Match) or 0.0 (Mismatch) for VAPO optimization.
    """
    # 1. Try to extract 'product_match' from the model response.
    # The model response might be a raw JSON string like:
    # {"product_in_reference_image" : "...", "product_in_candidate_image" : "...", "product_match" : "Match", "reason" : "..."}
    
    extracted_match = ""
    try:
        # Preprocess text to parse JSON if wrapped in markdown blocks
        cleaned_text = str(model_response_text).strip()
        cleaned_text = cleaned_text.replace("```json","").replace("```","").strip()
        
        response_json = json.loads(cleaned_text)
        if isinstance(response_json, dict):
            extracted_match = response_json.get("product_match", "").strip()
    except Exception as e:
        # If parsing JSON fails, perhaps VAPO already extracted the specific value
        # using the `model_grade_key_in_output_json` path.
        logger.warning(f"JSON Parsing Failed: {e}. Falling back to raw text. Text: {str(model_response_text)[:100]}...")
        extracted_match = str(model_response_text).strip()

    if not extracted_match:
        return 0.0

    # 2. Normalize both strings to lower case for comparison
    mg_norm = extracted_match.lower()
    gt_norm = str(ground_truth).lower().strip()
    
    is_model_match = mg_norm == "match"
    is_gt_match = gt_norm == "match"
    
    # Binary Scoring Logic
    if is_model_match and is_gt_match:
        return 1.0
    elif not is_model_match and not is_gt_match:
        return 1.0
    else:
        # Match != Not_Match or Not_Match != Match
        return 0.0

@functions_framework.http
def product_match_custom_metric(request):
    """
    HTTP Cloud Function for Product Image Match Custom Metric (Match-Only Binary).
    
    Expected Input JSON Payload fields from VAPO:
    - response: The output generated by the model for the test instance.
    - target: The known ground truth.
    """
    try:
        request_json = request.get_json(silent=True)
        if not request_json:
            return {"error": "Invalid JSON"}, 400
            
        # Extract fields (VAPO standard names)
        response_text = request_json.get("response", "")
        ground_truth = request_json.get("target", "")
        
        if not response_text or not ground_truth:
            logger.warning("Missing 'response' or 'target' in payload.")
            return {"match_score": 0.0}

        # Calculate Score
        score = evaluate_product_match(response_text, ground_truth)
        
        logger.info(f"Scored: {score} | GT: {ground_truth} | Model: {str(response_text)[:50]}...")

        return {"match_score": score}

    except Exception as e:
        logger.error(f"Error in product_match_custom_metric: {e}")
        return {"error": str(e)}, 500
